image: python:3.9

stages:
  - test
  - docs

before_script:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install pytest pytest-cov mkdocs-material

test:
  stage: test
  script:
    - pytest --cov=qakeapi tests/ --cov-report=xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

docs:
  stage: docs
  script:
    - mkdocs build --strict
  artifacts:
    paths:
      - site/ 